### ARRAY CREATION

Alternative Methods to Create Arrays.

+ `np.ones((rows,cols), dtype)`  :--ones :- Create an array of ones of a given size, defaultly of floats.
+ `np.zeros((rows,cols), dtype)` :--zeros :- Create an array of zeros of a given size, defaultly of floats.
+ `np.arange(start, stop, step)` :--arange :- Create an array of integers with start, stop, and step.
+ `np.linspace(start, stop, n)` :--linspace :- Create an array of floats with start, stop and step.
+ `np.array.reshape(rows, cols)` :--changes an array to specified dimension, if compatible

In [5]:
import numpy as np
from functions import *

In [6]:
## ones
ones = np.ones((100,200), dtype = "float")
array_key_properties(ones)

 number of dimensions in an array (axes). :-- 2
 size of the array in each dimensions. :-- (100, 200)
 total number of elements in the array. :-- 20000
 data type of the element in the array. :-- float64


In [7]:
## zeros
zeros = np.zeros((10,20), dtype = "int")
array_key_properties(zeros)

 number of dimensions in an array (axes). :-- 2
 size of the array in each dimensions. :-- (10, 20)
 total number of elements in the array. :-- 200
 data type of the element in the array. :-- int32


In [12]:
## arange
array_from_to = np.arange(100,200,2)
print(array_from_to)
array_key_properties(array_from_to)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198]
 number of dimensions in an array (axes). :-- 1
 size of the array in each dimensions. :-- (50,)
 total number of elements in the array. :-- 50
 data type of the element in the array. :-- int32


In [17]:
## linspace
linspace = np.linspace(99,200,100)
print(linspace)
array_key_properties(linspace)

[ 99.         100.02020202 101.04040404 102.06060606 103.08080808
 104.1010101  105.12121212 106.14141414 107.16161616 108.18181818
 109.2020202  110.22222222 111.24242424 112.26262626 113.28282828
 114.3030303  115.32323232 116.34343434 117.36363636 118.38383838
 119.4040404  120.42424242 121.44444444 122.46464646 123.48484848
 124.50505051 125.52525253 126.54545455 127.56565657 128.58585859
 129.60606061 130.62626263 131.64646465 132.66666667 133.68686869
 134.70707071 135.72727273 136.74747475 137.76767677 138.78787879
 139.80808081 140.82828283 141.84848485 142.86868687 143.88888889
 144.90909091 145.92929293 146.94949495 147.96969697 148.98989899
 150.01010101 151.03030303 152.05050505 153.07070707 154.09090909
 155.11111111 156.13131313 157.15151515 158.17171717 159.19191919
 160.21212121 161.23232323 162.25252525 163.27272727 164.29292929
 165.31313131 166.33333333 167.35353535 168.37373737 169.39393939
 170.41414141 171.43434343 172.45454545 173.47474747 174.49494949
 175.51515

In [21]:
## reshape
array = np.arange(100,200,2)
print(array)
array.reshape(5,10)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198]


array([[100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198]])

### RANDOM NUMBER GENERATION

You can Create random number arrays of variety of Distribution using NumPy functions and Methods.

1. default_rng :-- Create Random Number Generator.

    `np.default_rng(seed)`
    
2. random :-- Return n random numbers from a uniform distribution between 0 and 1.

    `rng.random(n)`
    
3. normal :-- Return n random numbers from a normal distribution with a given mean and standard deviation.

    `rng.normal(mean,stdev,n)`

In [23]:
from numpy.random import default_rng

In [28]:
rng = default_rng(12345)
#print(rng)
random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [29]:
rng = default_rng(12345)
mean, stdev = 5, 1
random_normal = rng.normal(mean, stdev, size = 10)
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

#### ASSIGNMENT

In [37]:
array = np.linspace(10,100,10, dtype = "int")
print(array)
print(array.reshape(5,2))

[ 10  20  30  40  50  60  70  80  90 100]
[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [36]:
random_array = rng.random(9)
random_array.reshape(3,3)

array([[0.22013496, 0.08159457, 0.1598956 ],
       [0.34010018, 0.46519315, 0.26642103],
       [0.8157764 , 0.19329439, 0.12946908]])