### INDEXING AND SLICING

+ Indexing and Slicing of `1D` array is same as Python List and Tuples.

+ `array[index]` :-- index to access single element.
+ `array[start : stop : step_size ]` :-- Slicing to access a Series of element.

In [8]:
import numpy as np
from numpy.random import default_rng
import random

In [3]:
product_list = ["fruits", "vegetables", "cereal", "dairy", "eggs", "snacks", "beverages", "coffee", "tea", "spices"]
product_array = np.array(product_list)
print(product_array[1])
print(product_array[-1])
print(product_array[:5])
print(product_array[5::2])

vegetables
spices
['fruits' 'vegetables' 'cereal' 'dairy' 'eggs']
['snacks' 'coffee' 'spices']


+ Indexing and Slicing of `2D` array requires an extra index or slice.

+ `array[row_index,column_index]` :-- index to access single element.
+ `array[start : stop : step_size, start : stop : step_size]` :-- Slicing to access a Series of element.

In [6]:
product_array2D = product_array.reshape(2,5)
product_array2D

print(product_array2D[1,2])
print(product_array2D[:,2:])
print(product_array2D[1:,:])

coffee
[['cereal' 'dairy' 'eggs']
 ['coffee' 'tea' 'spices']]
[['snacks' 'beverages' 'coffee' 'tea' 'spices']]


### ASSIGNMENT

In [12]:
rng = default_rng(12345)
random_array = rng.random(9)
array = random_array.reshape(3,3)
array

array([[0.22733602, 0.31675834, 0.79736546],
       [0.67625467, 0.39110955, 0.33281393],
       [0.59830875, 0.18673419, 0.67275604]])

In [14]:
## index first two rows
array[0:2]

array([[0.22733602, 0.31675834, 0.79736546],
       [0.67625467, 0.39110955, 0.33281393]])

In [16]:
## first column values
array[:,0]

array([0.22733602, 0.67625467, 0.59830875])

In [20]:
## second number in third row
array[2:, 1]

array([0.18673419])