### ARITHMETIC OPERATIONS

In [9]:
import numpy as np

sales = [0, 5, 155,0, 518, 0, 1827, 616, 317, 325]
sales_array = np.array(sales)
sales_array = sales_array.reshape(2,5)

Addition

In [10]:
sales_array + 200

array([[ 200,  205,  355,  200,  718],
       [ 200, 2027,  816,  517,  525]])

Multiplcation

In [12]:
quantity = sales_array[0,:]
print(quantity)
price = sales_array[1,:]
print(price)

mult_array = quantity * price
print(mult_array)

[  0   5 155   0 518]
[   0 1827  616  317  325]
[     0   9135  95480      0 168350]


### ASSIGNMENT

In [13]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
total = prices + 5
print(total)

[ 10.99  11.99  27.49 104.99   9.99  54.99]


In [15]:
import numpy as np
from numpy.random import default_rng
import random

rng = default_rng(12345)
random_array = rng.random(9)
array = random_array.reshape(3,3)
array

array([[0.22733602, 0.31675834, 0.79736546],
       [0.67625467, 0.39110955, 0.33281393],
       [0.59830875, 0.18673419, 0.67275604]])

In [16]:
discount_pct = array[:2].reshape(6)
pct_owed = 1 - discount_pct
final_owed = total * pct_owed
final_owed.round(2)

array([ 8.49,  8.19,  5.57, 33.99,  6.08, 36.69])