### FILETRING AND MODIFYING ARRAY VALUES

+ We can filter arrays by Indexing them with a Logical Test.
+ We can use filter arrays with Multiple Logical Test.
+ We can use `| for OR` operation and `& for AND` operations.

Modifying the Array Values

+ You can modify the array values by assigning new values through indexing and we can also use the conditions as well.

In [4]:
import numpy as np

sales = [0, 5, 155,0, 518, 0, 1827, 616, 317, 325]
sales_array = np.array(sales)
sales_array = sales_array.reshape(2,5)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [5]:
## logical test
sales_array != 0

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [6]:
## so doing the indexing for the values only non-zero
sales_array[sales_array != 0]

array([   5,  155,  518, 1827,  616,  317,  325])

In [8]:
## both conditions applied
sales_array[(sales_array == 616) | (sales_array < 100)]

array([  0,   5,   0,   0, 616])

In [14]:
## both conditions applied
sales_array[(sales_array == 5) & (sales_array < 10)]

array([5])

In [15]:
## both conditions applied
sales_array[(sales_array > 100) & (sales_array < 500)]

array([155, 317, 325])

In [19]:
## boolean mask, using boolean mask
mask = (sales_array > 100) & (sales_array < 1000)
## filtering
sales_array[mask]

array([155, 518, 616, 317, 325])

Modifying the Array Values

In [25]:
sales = [0, 5, 155,0, 518, 0, 1827, 616, 317, 325]
sales_array = np.array(sales)
#sales_array = sales_array.reshape(2,5)
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [26]:
sales_array[1] = 25
sales_array

array([   0,   25,  155,    0,  518,    0, 1827,  616,  317,  325])

In [27]:
sales_array[0] = 25
sales_array

array([  25,   25,  155,    0,  518,    0, 1827,  616,  317,  325])

In [28]:
sales_array[sales_array == 0] = 100
sales_array

array([  25,   25,  155,  100,  518,  100, 1827,  616,  317,  325])

### THE WHERE FUNCTION

+ the where() function performs a Logical Test and returns
    + a given value if the test is True.
    + another value if the test is False.

In [29]:
num_list = [12, 102, 18, 0, 0]
inventory_array = np.array(num_list)
inventory_array

array([ 12, 102,  18,   0,   0])

In [36]:
product_list = ["fruits","vegetables","cereal","dairy","eggs"]
product_array = np.array(product_list)
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [37]:
np.where(
        inventory_array <= 0,
        "Out of Stock",
        "In Stock"
)

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [38]:
np.where(
        inventory_array <= 0,
        "Out of Stock",
        product_array
)

array(['fruits', 'vegetables', 'cereal', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

### ASSIGNMENTS

In [51]:
products = np.array([
    "salad","bread","mustard","rare tomato","cola","gourmet ice cream"
])

print(products)

prices = np.array([
    5.99, 6.99, 22.49, 99.99, 4.99, 49.99
])
print(prices)

## filter when teh price is greater than 25
print("The Products that has values greater than 25 :---",products[prices > 25])

## filter the product like inclusing the cola, and the prices greate than 25
mask = (prices > 25) | (products == "cola")
fancy_feast_special = products[mask]
print("The Products inclusing the Cola and the Proces are greater than 25 :---",products[mask])
print("The Fancy Feast Special :---", products[mask])

## we need to filter the price for shipping cost.
## if the priice is greater than 20, then the shipping cost is 0.
## if the price is below 20, then shipping costs 5.
shipping_array = np.where

['salad' 'bread' 'mustard' 'rare tomato' 'cola' 'gourmet ice cream']
[ 5.99  6.99 22.49 99.99  4.99 49.99]
The Products that has values greater than 25 :--- ['rare tomato' 'gourmet ice cream']
The Products inclusing the Cola and the Proces are greater than 25 :--- ['rare tomato' 'cola' 'gourmet ice cream']
The Fancy Feast Special :--- ['rare tomato' 'cola' 'gourmet ice cream']
