### ARRAY AGGREGATION

+ Array Aggregation method lets you Calculate metrics like,

        + sum()
        + mean()
        + max()
        + min()
        
+ You can aggregate across rows and columns.

        + axis = 0 means towards row.
        + axis = 1 means towards columns.

In [4]:
import numpy as np

sales_array = np.array([[0,5,155,0,518],[0,1827,616,317,325]])
sales_array

print("The Sum of the Values in the Array :--", sales_array.sum())
print("The Mean of the Values in the Array :--", sales_array.mean())
print("The Maximum Value in the Array :--", sales_array.max())
print("The Minimum Value in the Array :--", sales_array.min())

The Sum of the Values in the Array :-- 3763
The Mean of the Values in the Array :-- 376.3
The Maximum Value in the Array :-- 1827
The Minimum Value in the Array :-- 0


In [6]:
## taking the sum across the row and columns.
print("The Sum across Rows :---",sales_array.sum(axis = 0))
print("The Sum across Columns :---", sales_array.sum(axis = 1))

The Sum across Rows :--- [   0 1832  771  317  843]
The Sum across Columns :--- [ 678 3085]


### ARRAY FUNCTIONS

+ Array Functions let you Calculate Aggregations like median, percentiles, unique etc.

In [12]:
sales_array

## finding the median values.
print("The Median value of the Array :--", np.median(sales_array))
## finding the 90 th percentiles of the array.
print("The 90th Percentiles of the Array is :--", np.percentile(sales_array, 90))
print("The 75th Percentiles of the Array is :--", np.percentile(sales_array, 75))

## finding the unique value in the array
print("The unique Value present in the Array :--", np.unique(sales_array))

## sqrt values of the elements in the Array 
print("The Square Roots of the Values in the Array :---", np.sqrt(sales_array))

The Median value of the Array :-- 236.0
The 90th Percentiles of the Array is :-- 737.0999999999996
The 75th Percentiles of the Array is :-- 469.75
The unique Value present in the Array :-- [   0    5  155  317  325  518  616 1827]
The Square Roots of the Values in the Array :--- [[ 0.          2.23606798 12.4498996   0.         22.75961335]
 [ 0.         42.74342055 24.81934729 17.80449381 18.02775638]]


### SORTING ARRAYS

+ sort() method will sort arrays in place.
+ Use the axis to specify the dimension to sort by.

        + default axis = 1 --> Row Operation.
        + axis = 0 --> Column Operation.

In [19]:
sales_array = np.array([[0,5,155,0,518],[0,1827,616,317,325]])
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [20]:
sales_array.sort()
sales_array

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

In [21]:
## sales array sorted by columns 
sales_array.sort(axis = 0)
sales_array

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

### ASSIGNMENT

In [35]:
prices = np.array([
    5.99, 6.99, 22.49, 99.99, 4.99, 49.99
])
print(prices)

## sort the pprice array after that take the top three prices and do the min, max, mean, etc.
prices.sort()
print("Sorted Prices :--", prices)
top_three_prices = prices[3:]
print("Top three Prices :--", top_three_prices)

## print the mean
print("The Mean of the top three prices :--", top_three_prices.mean())
## print the min value in the top three array
print("The Minimum Value of the top three Array :--", top_three_prices.min())
## print the maximum value of th etop three .
print("The Maximum Value of the top three Array :--", top_three_prices.max())
## median
print("The Median Value of the top three Array :-", np.median(top_three_prices))

[ 5.99  6.99 22.49 99.99  4.99 49.99]
Sorted Prices :-- [ 4.99  5.99  6.99 22.49 49.99 99.99]
Top three Prices :-- [22.49 49.99 99.99]
The Mean of the top three prices :-- 57.49
The Minimum Value of the top three Array :-- 22.49
The Maximum Value of the top three Array :-- 99.99
The Median Value of the top three Array :- 49.99


In [38]:
## unique price tiers
price_tiers = np.array(["budget","budget","mid-tier","luxury","mid-tier","luxury"])
price_tiers

## unique price tiers
print("The Unique Price Tiers we have are :--", np.unique(price_tiers))

The Unique Price Tiers we have are :-- ['budget' 'luxury' 'mid-tier']
