### VECTORIZATION AND BROADCASTING

+ It is the Process of Pushing array Operation into Optimized C-code.
+ Which is easier and more Efficient than writing for Loops.

In [2]:
import pandas as pd
import numpy as np

In [15]:
def for_loop_multiply_lists(list1, list2):
    product_list = []
    for element1, element2 in zip(list1, list2):
        product_list.append(element1 * element2)
        
    return product_list

def multiply_arrays(array1, array2):
    return array1 * array2

In [10]:
list1 = list(range(1000))
list2 = list(range(1000))

In [11]:
%%timeit -r 5 -n 10000
for_loop_multiply_lists(list1, list2)

126 µs ± 774 ns per loop (mean ± std. dev. of 5 runs, 10000 loops each)


In [13]:
array1 = np.array(list1)
array2 = np.array(list2)

In [14]:
%%timeit -r 5 -n 10000
multiply_arrays(array1, array2)

1.86 µs ± 153 ns per loop (mean ± std. dev. of 5 runs, 10000 loops each)


### BROADCASTING

+ It lets you perform vectorized operations with arrays of different sizes.
+ Where NumPy will expand the smaller array to fit the LArger Array.
+ Single Values (scalars) can be Broadcasted into Arrays of any Dimension.

In [16]:
test_array = np.array([[1,2,3],[1,2,3],[1,2,3]])
test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [17]:
test_array + 1

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [18]:
test_array + np.array([[1,1,1],[1,1,1],[1,1,1]])

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [19]:
test_array + np.array([[3,2,1]])

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [20]:
test_array + np.array([3,2,1]).reshape(3,1)

array([[4, 5, 6],
       [3, 4, 5],
       [2, 3, 4]])